### ISSUE TITLE
Android Kotlin Fundamentals codelab: Getting data from internet

### ISSUE THREAD

**Issue by SamB78** [google-developer-training/android-kotlin-fundamentals-apps#79] opened 2020-03-20 14:38 UTC
**Describe the problem**
Miss this line " var listResult = getPropertiesDeferred.await()" in text after " The complete getMarsRealEstateProperties() method now looks like this:"

Lesson 8.1 task 6 11

**Comment by kkuan2011** [comment] 2020-08-11 08:11
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 08:11 UTC
