### ISSUE TITLE
Android Kotlin Fundamentals codelab: Getting data from the internet

### ISSUE THREAD

**Issue by i-Eugene** [google-developer-training/android-kotlin-fundamentals-apps#389] opened 2020-09-08 05:45 UTC
**Describe the problem**
Compile error "Interface Lazy does not have constructors"

**In which lesson and step of the codelab can this issue be found?**
kotlin-android-training-internet-data/#3 + Step 3: Implement MarsApiService

**How to reproduce?**
complete step 3, look at "lazy" on the line
I coding in a module with kotlin language, the host app module use java language.

**Versions**
1. Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Windows 10 10.0
2. targetSdkVersion/compileSdkVersion 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment] 2020-09-09 23:26
Thank you for reaching out to us. We are not able to reproduce this issue. Can you please provide more details?

**Comment by i-Eugene** [comment] 2020-09-10 01:05
> @i-Eugene
> Thank you for reaching out to us. We are not able to reproduce this issue. Can you please provide more details?

---------------------this is my kotlin code--------------------------
`private val retrofit = Retrofit.Builder()
        .addConverterFactory(ScalarsConverterFactory.create())
        .baseUrl(BASE_URL)
        .build()

interface ApiService {

    @GET("sug")
    fun getSuggest() : Call<String>
}

object Api {
    val retrofitService : ApiService by Lazy {
        retrofit.create(ApiService::class.java)
    }
}`
---------------------this is compile error-----------------------
`> Task :KotlinLab:compileDebugKotlin FAILED
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1e: E:\workspace\source\MyApplication\KotlinLab\src\main\java\com\ieugene\kotlinlab\network\ApiService.kt: (22, 41): Interface Lazy does not have constructors`

**Comment by i-Eugene** [comment] 2020-09-10 03:03
I see, it is different between "**Lazy**" and "**lazy**"
my misstake -_-#

**Comment by jtavva** [comment] 2020-09-10 17:22
Thank you for reaching out to us.  
Not reproducible, so closing the isssue!

**Closed by jtavva** 2020-09-10 17:22 UTC
Labels: Not reproducible
