### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by mbegabolawe** [google-developer-training/android-kotlin-fundamentals-apps#157] opened 2020-05-11 07:04 UTC
**Describe the problem**
The codelab uses deprecated `ViewModelProviders`.of instead of `ViewModelProvider` or rather `by viewModels`

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory
Step 9

**How to reproduce?**
n/a

**Versions**
n/a

**Additional information**
Can't find clarity between `ViewModelProvider` or rather `by viewModels`. I believe `by viewModels` is best practice.

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment] 2020-05-14 21:05
Duplicate of #29

**Closed by GeneAndGoogle** 2020-05-14 21:05 UTC
Labels: duplicate
