### ISSUE TITLE
Android Kotlin Fundamentals codelab: Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory

### ISSUE THREAD

**Issue by Adventures-in-Kotlin** [google-developer-training/android-kotlin-fundamentals-apps#29] opened 2020-02-08 20:31 UTC
**Describe the problem**
The code used to initialise the ViewModel is depreciated.
viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory

This code seems to work
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)

Refer to StackOverflow:
https://stackoverflow.com/questions/53903762/viewmodelproviders-is-deprecated-in-1-1-0

**How to reproduce?**
![ViewModelProviders](https://user-images.githubusercontent.com/46635372/74091678-d7cf2380-4b1e-11ea-9f63-77e55dada3fb.png)

Enter the code into Android Studio

**Versions**
1. What version of Android Studio are you using? 3.5.3
2. What API level are you targeting?
Min: 19
Max: 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 04:10
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 04:10 UTC
