### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by TamerBorg** [google-developer-training/android-kotlin-fundamentals-apps#207] opened 2020-06-14 16:16 UTC
**Describe the problem**
Android Kotlin Fundamentals 04.2: Complex lifecycle situations
Task: Simulate app shutdown and use onSaveInstanceState()
the code not working
sorry plz fix it :) 👍

**Comment by kkuan2011** [comment] 2020-08-11 08:53
Duplicate of #283

**Closed by kkuan2011** 2020-08-11 08:53 UTC
