### ISSUE TITLE
Android Kotlin Fundamentals codelab: 05.1 ViewModelProviders deprecated

### ISSUE THREAD

**Issue by EricTGoto** [google-developer-training/android-kotlin-fundamentals-apps#236] opened 2020-06-29 17:25 UTC
**Describe the problem**
A clear and concise description of what the problem is.

ViewModelProviders.of is deprecated so we should use ViewModelProvider instead

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
5.1 step 5

**How to reproduce?**
What are the exact steps to reproduce the problem?
Just follow the steps on the page and you'll see the deprecation

**Versions**
1. What version of Android Studio are you using? latest
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by ipshitaRB** [comment] 2020-07-02 16:42
Duplicate of  [#33](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/33)

**Comment by kkuan2011** [comment] 2020-08-11 06:35
Yup it's a duplicate, thanks for reporting!

**Closed by kkuan2011** 2020-08-11 06:35 UTC
