### ISSUE TITLE
Android Kotlin Fundamentals codelab: Kotlin Android Fundamentals 10.3: Design for everyone

### ISSUE THREAD

**Issue by EmilioNegron** [google-developer-training/android-kotlin-fundamentals-apps#254] opened 2020-07-16 00:36 UTC
**Describe the problem**
URL used in step produces a network 404 error.

**In which lesson and step of the codelab can this issue be found?**
Kotlin Android Fundamentals 10.3: Design for everyone == "Step 2: Use start and end instead of left and right"

**How to reproduce?**
add suggested code, and run app

**Versions**
1. What version of Android Studio are you using? 4.0
2. What API level are you targeting? 20

**Additional information**
Thank You for all you do!

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:52
Duplicate of #269

**Closed by kkuan2011** 2020-08-11 05:52 UTC
