### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/android-kotlin-fundamentals-apps#85] opened 2020-03-29 10:59 UTC
**Describe the problem**
Codelab state I should see "Application terminated" in the Run tab, but I don't. The last line of the Run tab states "I/MainActivity: onStop Called"

**In which lesson and step of the codelab can this issue be found?**
04.2, Step 5 "Task: Simulate app shutdown and use onSaveInstanceState()", Item #5

**How to reproduce?**
I followed the steps in the code lab.

**Versions**
1. What version of Android Studio are you using? 3.6.3
2. What API level are you targeting? targetSdkVersion 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by flplatet** [comment] 2020-04-13 23:15
It seems for `adb shell am kill com.example.android.dessertclicker` to be executed you need to have root access.

I guess it's not your case as well, so you can still run :
`adb shell run-as com.example.android.dessertclicker kill <pid>`
The pid is visible in AndroidStudio, in the Logcat tab when the app is running, besides the package name in the package dropdown filter

That's hacky but it's the only simple solution one I've found so far.

**Comment by kkuan2011** [comment] 2020-08-11 06:37
Duplicate of #156

**Closed by kkuan2011** 2020-08-11 06:37 UTC
