### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by giladoved** [google-developer-training/android-kotlin-fundamentals-apps#139] opened 2020-05-01 03:35 UTC
**Describe the problem**
Not necessarily a problem but `ViewModelProviders.of(this)` is deprecated. Would recommend updating the codelab to use the updated `ViewModelProvider(this)` instead.

**In which lesson and step of the codelab can this issue be found?**
5.1

**How to reproduce?**
What are the exact steps to reproduce the problem?
Can be seen in [this codelab](https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/index.html?index=..%2F..android-kotlin-fundamentals#4)

**Versions**
1. What version of Android Studio are you using?
3.6.3
2. What API level are you targeting?
28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment] 2020-05-14 21:04
Duplicate of #29

**Closed by GeneAndGoogle** 2020-05-14 21:04 UTC
Labels: duplicate
