### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by manit815** [google-developer-training/android-kotlin-fundamentals-apps#183] opened 2020-05-30 13:23 UTC
**Describe the problem**
Android Kotlin Fundamentals 01.3: Image resources and compatibility 5. Task: Use a default image has got few references to activity_layout.xml which should be activity_main.xml inside layout folder

There is a typo as well at step no.7 which should be dice instead of die.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.3: Image resources and compatibility 5. Task: Use a default image 

**How to reproduce?**
Referring to the documentation provided would help. 

**Versions**
NA

**Additional information**
NA

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:51
Duplicate of #114

**Closed by kkuan2011** 2020-08-11 07:51 UTC
