### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by AhmedAshour** [google-developer-training/android-kotlin-fundamentals-apps#70] opened 2020-03-11 19:04 UTC
**Describe the problem**
According to the [documentation](https://developer.android.com/jetpack/androidx/releases/lifecycle#declaring_dependencies):

> The APIs in lifecycle-extensions have been deprecated

So in the `ViewModel and ViewModelFactory` codelab (5. Task: Create the GameViewModel), the dependency of `ViewModel` should be changed from:
```
//ViewModel
implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
```
to:
```
// ViewModel
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
```

Also, the `ViewModelProviders.of()` is deprecated so instead of:
```
Log.i("GameFragment", "Called ViewModelProviders.of")
viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)
``` 
should be changed to:
```
Log.i("GameFragment", "Called ViewModelProviders.of")
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)
```

**In which lesson and step of the codelab can this issue be found?**
Lesson number: **05.1**
Step number: **5**

**How to reproduce?**
Open the lesson

**Versions**
1. What version of Android Studio are you using? **Not relevant**
2. What API level are you targeting? **Not relevant**

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by Patrick-Wallin** [comment] 2020-03-15 18:37
Perfect! It works! If you could not compile it, do not forget to remove import for ViewModelProviders.

**Comment by flplatet** [comment] 2020-04-13 23:27
Duplicate of #29

**Closed** 2020-05-14 21:02 UTC
Labels: duplicate
