### ISSUE TITLE
Android Kotlin Fundamentals codelab: save/restore bundle does not restore values because Bundle=null

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#283] opened 2020-08-03 21:23 UTC
**Describe the problem**
A clear and concise description of what the problem is.
In this section it uses onSaveInstanceState(outState:Bundle) to save 3 parameters for the dessertclicker app.  The save is successful, as I printed the value of outState after the putInt() calls were made.  However, when the app is resumed after being killed while in the background, the onCreate Bundle is null, so it never restores the value, and the app starts as if it started from scratch.

**In which lesson and step of the codelab can this issue be found?**
Lesson number Android Kotlin Fundamentals 04.2: Complex lifecycle situations + step number 5. Task: Simulate app shutdown and use onSaveInstanceState()

**How to reproduce?**
Follow the instructions on this task:

1. Run app after modifying it to save and restore parameters in Bundle
2. Tap Home button after running app and tapping on the dessert 5 times.
3. In Terminal run: adb shell am kill com.example.android.dessertclicker
4. Restore the app using the Recents list.

Result: App starts out with $0 instead of $25 , because Bundle is null on restart
Expected: App resume with $25 and donut showing 
(I'm running on Mac if that makes a difference)

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**
Attaching my dessert clicker MainActivity.kt

[MainActivity.kt.zip](https://github.com/google-developer-training/android-kotlin-fundamentals-apps/files/5018722/MainActivity.kt.zip)

**codelab:** android-kotlin-fundamentals

**Comment by HerreraManuel** [comment] 2020-08-06 00:17
I'm having the same issue with savedInstanceState returning null. However, I'm able to get the correct values after repeating the process twice.

1. Run app
2. Click the desserts 5 times
3. Click the Home button
4. Run the adb command
5. Restore the app using the Recents list
6. Click the dessert 7 times.
7. Click the Home button
8. Run the adb command
9. Restore the app using the Recents list.
10. The app now returns the amounts saved from clicking the dessert 7 times.

It's still a problem that should be fixed. I also noticed that it returns the amounts correctly on the first try when running the app in debug mode.

**Comment by jdelliot** [comment] 2020-08-10 19:08
Seeing the exact same behavior. Tried it in the final project (had to update gradle plugin), but result was exactly the same.

Would be great to understand what is happening here and what the expected behavior should be.

**Comment by alexcohn** [comment] 2020-08-12 10:57
See *[savedInstanceState is null after first app shutdown but not after second](https://stackoverflow.com/a/63375053/192373)*

**Comment by jtavva** [comment] 2020-11-04 19:17
Duplicate of #241


Thank you for reporting this issue, yes when you run the app from Android Studio, OS treats it differently.
To simulate the app shutdown we have updated the instructions and will be published soon.

**Closed by jtavva** 2020-11-04 19:17 UTC
Labels: Documentation issue
