### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Rob192** [google-developer-training/android-kotlin-fundamentals-apps#121] opened 2020-04-23 10:09 UTC
when running this code, the GameFragmentDirection is not found. In order to fix this I add to change the apply for the build.gradle for the app module to 
apply plugin: 'androidx.navigation.safeargs.kotlin'

**Comment by kkuan2011** [comment] 2020-08-11 08:50
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 08:50 UTC
