### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by JoeCodeswell** [google-developer-training/android-kotlin-fundamentals-apps#66] opened 2020-03-09 16:35 UTC
**Describe the problem**
A clear and concise description of what the problem is.
1. codelab says "In the Configure your project dialog, name the app whatever you'd like. Select Kotlin for the language, and select the Use AndroidX artifacts checkbox. Click Finish."
2. Android Studio 3.6.1 DOES NOT HAVE *"Use AndroidX artifacts" checkbox*.
  - It does have *"Use legacy android.support libraries" checkbox*.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
- Android Kotlin Fundamentals 01.4: Learn to help yourself
  - 3. Task: Use project templates
    - Step 1: Explore the Basic Activity architecture
  

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using? 3.6.1
2. What API level are you targeting?  28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:26
Duplicate of #278

**Closed by kkuan2011** 2020-08-11 06:26 UTC
