### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by SebDrobisz** [google-developer-training/android-kotlin-fundamentals-apps#276] opened 2020-07-30 09:37 UTC
**Describe the problem**
Wrong classpath (`android.arch.navigation` instead of `androidx.navigation`)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.3 - step 2 (point 2) 

**How to reproduce?**
What are the exact steps to reproduce the problem?
/

**Versions**
1. What version of Android Studio are you using? **4.0**
2. What API level are you targeting? **30**

**Additional information**
/

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:14
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 08:14 UTC
