### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Srkanna** [google-developer-training/android-kotlin-fundamentals-apps#244] opened 2020-07-05 09:44 UTC
While adding **app:srcCompat="@drawable/empty_dice"** as instructed in the lesson, the dice image design section disappears even though I have used **tools:src="@drawable/dice_1"**

**In which lesson and step of the codelab can this issue be found?**
6 + 5.

**How to reproduce?**
set VectorDrawables:useSupportLibrary to true in build.gradle file and app:srcCompat instead of android:src in activity_main.xml

**Versions**
1. 3.6.1
2. 29

**Additional information**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-images-compat/#5

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:02
Duplicate of #56

**Closed by kkuan2011** 2020-08-11 08:02 UTC
