### ISSUE TITLE
Android Kotlin Fundamentals codelab: AndroidX package names in Lesson 3.3, Task 3, Step 2

### ISSUE THREAD

**Issue by danidim13** [google-developer-training/android-kotlin-fundamentals-apps#285] opened 2020-08-04 01:40 UTC
**Describe the problem**
Package naming is inconsistent with new AndroidX package naming.

In the code snippet for adding the `navigation-safe-args-gradle-plugin`, the old `android.arch` package name is used
```
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}
```

Later on the plugin is applied using the new AndroidX package name.

In the above snipped it should be `classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**In which lesson and step of the codelab can this issue be found?**
Lesson 3.3, Task 3, Step 2: Add Safe Args to the project

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
Android Studio 4.0.1

2. What API level are you targeting?
API 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:45
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 05:45 UTC
