### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by davidwekesar** [google-developer-training/android-kotlin-fundamentals-apps#222] opened 2020-06-24 08:58 UTC
**codelab:** android-kotlin-fundamentals

**Initializing a ViewModel object using ViewModelProviders.of() method.**

In the codelab the GameFragment ViewModel  is initalized like this:

    viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)

The ViewModelProviders.of() method seems to be deprecated and now a ViewModel is initialized a followed:

    viewModel = ViewModelProvider(this).get(GameViewModel::class.java)

**The issue is found in:**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory, Lesson 5, Step 3.

**Versions:**
1. Android Studio 4.0
2. Target SDK version: 29

**Comment by kkuan2011** [comment] 2020-08-11 06:00
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 06:00 UTC
