### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by shubhamji88** [google-developer-training/android-kotlin-fundamentals-apps#204] opened 2020-06-12 17:11 UTC
**The Problem**
As written in Codelab:
Inside the try {} block, call await() on the Deferred object:
var listResult = getPropertiesDeferred.await()

and after this, there is written :

The complete getMarsRealEstateProperties() method now looks like this:

private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}

This can be found on codelab "Android Kotlin Fundamentals 08.1: Getting data from the internet"
Lesson number-8
 step number-6(Task: use coroutines with retrofit)

**The exact steps to reproduce the problem is:**
replacing one line inside the try block and the function should be:
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           var listResult = getPropertiesDeferred.await()
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}

**Versions**
1. What version of Android Studio are you using?
4.0 for Windows 64-bit
2. What API level are you targeting?
28

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:48
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 08:48 UTC
