### ISSUE TITLE
Android Kotlin Fundamentals codelab: "3.3: Start an external activity" Gradle Sync Error

### ISSUE THREAD

**Issue by Osunator** [google-developer-training/android-kotlin-fundamentals-apps#340] opened 2020-08-24 20:05 UTC
**Describe the problem**
The SafeArgs dependency code is incorrect, is says 
        classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
but it gives error when trying to sync, it should be 
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

**In which lesson and step of the codelab can this issue be found?**
On "3.3: Start an external activity" at the "Task: Set up and use the Safe Args plugin" on Step 2

**How to reproduce?**
Just use the code given in the codelab and the gradle sync is unable to complete

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 14

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment] 2020-09-15 00:58
Dupl
Thank you for reaching out to us.
Duplicate of #399

**Closed by jtavva** 2020-09-15 00:58 UTC
Labels: duplicate
