### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by nicol-ograve** [google-developer-training/android-kotlin-fundamentals-apps#39] opened 2020-02-13 23:00 UTC
**Describe the problem**
await missing

**In which lesson and step of the codelab can this issue be found?**
Lesson 08.1.6 - Step 2.11 

**How to reproduce?**

```
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           // This instruction is missing: var listResult = getPropertiesDeferred.await()
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}
```

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:02
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:02 UTC
