### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by TamerBorg** [google-developer-training/android-kotlin-fundamentals-apps#106] opened 2020-04-14 18:03 UTC
**Describe the problem**
viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)
update to
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)

**In which lesson and step of the codelab can this issue be found?**
https://codelabs.developers.google.com/codelabs/kotlin-android-training-view-model/index.html?index=..%2F..android-kotlin-fundamentals#4

**Comment by GeneAndGoogle** [comment] 2020-05-14 21:04
Duplicate of #29

**Closed by GeneAndGoogle** 2020-05-14 21:04 UTC
Labels: duplicate
