### ISSUE TITLE
Android Kotlin Fundamentals codelab: wrong type referenced in getViewById calls

### ISSUE THREAD

**Issue by Nixon-Joseph** [google-developer-training/android-kotlin-fundamentals-apps#71] opened 2020-03-13 23:43 UTC
**Describe the problem**
The code in the step describes getting views by id, but the type referenced into getViewById<>() is TextView, when the previous step had those id's assigned to Buttons.

**In which lesson and step of the codelab can this issue be found?**
Lesson: Android Kotlin Fundamentals 02.3: Constraint layout using the Layout Editor
Step: 12 -> part 2

**How to reproduce?**
No action required.

**Versions**
1. What version of Android Studio are you using? N/A
2. What API level are you targeting? N/A

**Additional information**
Issue in the lesson, not implementation of the lesson.

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:19
Duplicate of #133

**Closed by kkuan2011** 2020-08-11 06:19 UTC
