### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by mahabubulhasan** [google-developer-training/android-kotlin-fundamentals-apps#151] opened 2020-05-09 15:16 UTC
**Describe the problem**
This is a mistake in the sample code, on point 11 just after this line 
>`The complete getMarsRealEstateProperties()` method now looks like this:

```kotlin
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           _response.value = 
              "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}
```
here the `var listResult = getPropertiesDeferred.await()` part is missing.

**In which lesson and step of the codelab can this issue be found?**
Lesson number: Android Kotlin Fundamentals 08.1
step number: 11

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:17
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 08:17 UTC
