### ISSUE TITLE
Android Kotlin Fundamentals Codelab 08.1: 

### ISSUE THREAD

**Issue by Jono1954** [google-developer-training/android-kotlin-fundamentals-apps#93] opened 2020-04-07 08:00 UTC
**Describe the problem**
A line of code seems to be missing in one of the code listings

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 08.1: 
6. Task: Use coroutines with Retrofit
Step 2: Update MarsApiService and OverviewViewModel
Para 11

    The complete getMarsRealEstateProperties() method now looks like this:

    private fun getMarsRealEstateProperties() {
            coroutineScope.launch {
                // Get the Deferred object for our Retrofit request
                var getPropertiesDeferred = MarsApi.retrofitService.getProperties()
                try {
    
    // Possible missing line of code?
                    // Await the completion of our Retrofit request
                    var listResult = getPropertiesDeferred.await() 
    
                    _response.value = "Success: ${listResult.size} Mars properties retrieved"
                } catch (e: Exception) {
                    _response.value = "Failure: ${e.message}"
                }
            }
        }

Thanks

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:09
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:09 UTC
