### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by dape1133** [google-developer-training/android-kotlin-fundamentals-apps#266] opened 2020-07-24 20:21 UTC
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals
override fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater?.inflate(R.menu.options_menu,menu)
    }

    override fun onOptionsItemSelected(item: MenuItem?): Boolean {
        return NavigationUI.onNavDestinationSelected(item!!,view!!.findNavController())
                ||super.onOptionsItemSelected(item)
------------------------
FIXED
REMOVE THE "?"
override fun onCreateOptionsMenu(menu: Menu, inflater: MenuInflater) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater.inflate(R.menu.options_menu,menu)
    }

    override fun onOptionsItemSelected(item: MenuItem): Boolean {
        return NavigationUI.onNavDestinationSelected(item!!,view!!.findNavController())
                ||super.onOptionsItemSelected(item)

**Comment by kkuan2011** [comment] 2020-08-11 07:42
Duplicate of #209

**Closed by kkuan2011** 2020-08-11 07:42 UTC
