### ISSUE TITLE
Android Kotlin Fundamentals codelab: Dead Server Link

### ISSUE THREAD

**Issue by dc172088** [google-developer-training/android-kotlin-fundamentals-apps#293] opened 2020-08-06 23:33 UTC
**Describe the problem**
https://developers.google.com/community/gdg/groups/directory.json is a dead link. I was unable to fetch any data.

**In which lesson and step of the codelab can this issue be found?**
lesson 10.3 + step 6.

**How to reproduce?**
After clicking on the FAB to get to the list of Google Dev Groups, the app crashed. Logcat indicated that "retrofit2.HttpException: HTTP 404"
 

**Versions**
1. What version of Android Studio are you using? 4.01
2. What API level are you targeting? 25

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 03:58
Duplicate of #269

**Closed** 2020-08-11 03:58 UTC
