### ISSUE TITLE
Android Kotlin Fundamentals codelab: 04.2: Complex lifecycle situations

### ISSUE THREAD

**Issue by SavaSoftware** [google-developer-training/android-kotlin-fundamentals-apps#241] opened 2020-07-02 14:52 UTC
**Describe the problem**
After sending the application to the background and shutting down the process the stats are not saved. I thought it was my bad and copy pasted the code from the solution, causing the same behavior. Can someone help? :)

**In which lesson and step of the codelab can this issue be found?**
04.2 Task 5.9

**How to reproduce?**
?

**Versions**
1. What version of Android Studio are you using? 4.0
2. What API level are you targeting? 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by runaloop** [comment] 2020-08-09 10:01
I have the very same problem, asked the question on [stackoverflow](https://stackoverflow.com/questions/63314078/minimizing-app-with-home-calls-onsaveinstancestate-but-when-going-to-app-aga) but no answer yet, do you have any solution?

**Comment by SavaSoftware** [comment] 2020-08-09 12:27
I just moved on without a solution. I would advise you to do the same because the course will introduce you to a better way of handling this problems in your apps.

**Comment by alexcohn** [comment] 2020-08-15 17:47
can be marked duplicate of https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/283

**Comment by SavaSoftware** [comment] 2020-08-15 18:29
How can this thread be a duplicate of a much younger thread? @alexcohn

**Comment by alexcohn** [comment] 2020-08-15 18:34
@kkuan2011 already marked https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/86 and https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/207 duplicates of the same https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/283. It doesn't really matter which issue is closed and which remains, as long as the issue is taken care of.

**Comment by ikanchev1** [comment] 2020-10-21 12:16
I am doing this course in late 2020 and i am surprised to find this bug is still there. 5 years later from the looks of it..

**Comment by jtavva** [comment] 2020-11-04 19:15
@alexcohn @ikanchev1 @runaloop @SavaSoftware 
Thank you for reporting this issue, yes when you run the app from Android Studio, OS treats it differently. 
To simulate the app shutdown we have updated the instructions and will be published soon.

**Closed by jtavva** 2020-11-04 19:15 UTC
Labels: In progress
