### ISSUE TITLE
Android Kotlin Fundamentals codelab: Start an external activity

### ISSUE THREAD

**Issue by Systemad** [google-developer-training/android-kotlin-fundamentals-apps#208] opened 2020-06-15 19:57 UTC
**Describe the problem** 
***KOTLIN***
A clear and concise description of what the problem is.
`apply plugin: "androidx.navigation.safeargs.kotlin"` should be used instead of  
`apply plugin: 'androidx.navigation.safeargs'`  otherwise will cause a 'too many arguments' error in

`
                        view.findNavController()
                                .navigate(GameFragmentDirections
                                        .actionGameFragmentToGameWonFragment(numQuestions, questionIndex))
`

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:07
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 06:07 UTC
