### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by hi-mod** [google-developer-training/android-kotlin-fundamentals-apps#34] opened 2020-02-11 16:23 UTC
**Describe the problem**
ViewModelProviders.of is deprecated

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory Step 8

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by flplatet** [comment] 2020-04-13 23:27
Duplicate of #29

**Closed** 2020-05-14 21:28 UTC
Labels: duplicate
