### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by joseantoniocampillo** [google-developer-training/android-kotlin-fundamentals-apps#88] opened 2020-04-01 09:21 UTC
**Describe the problem**
A clear and concise description of what the problem is.

**In which lesson and step of the codelab can this issue be found?**
08.1: (Getting data from the internet). Step 6

**How to reproduce?**
a line / sentence is missing

**Additional information**
Before the end. Under the line:
"The complete getMarsRealEstateProperties() method now looks like this:"
That method needs this sentence:
"var listResult = getPropertiesDeferred.await()"

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:01
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:01 UTC
