### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by beriaanirudh** [google-developer-training/android-kotlin-fundamentals-apps#274] opened 2020-07-29 14:08 UTC
**Describe the problem**
Missing line in code example on Page ahttps://codelabs.developers.google.com/codelabs/kotlin-android-training-internet-data/index.html?index=..%2F..android-kotlin-fundamentals#5 . The complete **getMarsRealEstateProperties** will have this additional line 
var listResult = getPropertiesDeferred.await()

// Following details are redundant. 

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:27
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:27 UTC
