### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Encryptor** [google-developer-training/android-kotlin-fundamentals-apps#53] opened 2020-02-26 16:31 UTC
**Describe the problem**
A clear and concise description of what the problem is.
**Inside getMarsRealEstateProperties() method, the following line is missing in the try block
           var listResult = getPropertiesDeferred.await()**

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
**Android Kotlin Fundamentals 08.1: Getting data from the internet + 6**

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:05
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:05 UTC
