### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by danielcyc** [google-developer-training/android-kotlin-fundamentals-apps#189] opened 2020-06-02 10:57 UTC
**Describe the problem**
A clear and concise description of what the problem is.

Typo instructions `main_activity.xml` should be `activity_main.xml` in point 4

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.

Lesson 01.3, step 6
**How to reproduce?**
What are the exact steps to reproduce the problem?
Open the page
**Versions**
1. What version of Android Studio are you using? 4.0
2. What API level are you targeting? 28

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:44
Duplicate of #114

**Closed by kkuan2011** 2020-08-11 08:44 UTC
