### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by jdelliot** [google-developer-training/android-kotlin-fundamentals-apps#297] opened 2020-08-09 21:59 UTC
**Describe the problem**
semi colon termination kotlin statement

**In which lesson and step of the codelab can this issue be found?**
4.2 + 3.

**How to reproduce?**
in the code snipet:
```kotlin
private lateinit var dessertTimer : DessertTimer;
```

**Versions**
1. What version of Android Studio are you using? N/A
2. What API level are you targeting? N/A

**Additional information**
N/A

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:28
Duplicate of #104

**Closed by kkuan2011** 2020-08-11 08:28 UTC
