### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by takeclassic** [google-developer-training/android-kotlin-fundamentals-apps#129] opened 2020-04-26 07:28 UTC
-There is no Gallery in java right click menu
- Android Kotlin Fundamentals 01.4: Learn to help yourself -> Task 3 -> Step 3
-Contents is different to explanation of page

**Versions**
1. What version of Android Studio are you using?
3.6.3
2. What API level are you targeting?
29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by GeneAndGoogle** [comment] 2020-05-14 20:35
Can you confirm your version and that you still see the problem? I just tried in AS 3.6.3 and it works as described:
2. In the **Project > Android pane**, right-click on the java folder. 
3. Select **New > Activity > Gallery**.

<img width="1128" alt="new activity gallery" src="https://user-images.githubusercontent.com/54457695/81983012-889a0280-95e7-11ea-9f70-9ead494e3238.png">

**Comment by kkuan2011** [comment] 2020-08-11 07:48
Hello, since we don't have further details on how to reproduce this error, we'll have to close this bug. But feel free to reopen if you still see this issue, thanks!

**Closed by kkuan2011** 2020-08-11 07:48 UTC
