### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by DMDone** [google-developer-training/android-kotlin-fundamentals-apps#612] opened 2021-03-24 16:43 UTC
**Name of the Codelab or Codelab URL**
Android Kotlin Fundamentals: 02.3 ConstraintLayout using the Layout Editor
https://developer.android.com/codelabs/kotlin-android-training-constraint-layout/index.html#11

**Describe the problem**
Instead of:
R.id.red_button -> box_three_text.setBackgroundResource(R.color.my_red)
R.id.yellow_button -> box_four_text.setBackgroundResource(R.color.my_yellow)
R.id.green_button -> box_five_text.setBackgroundResource(R.color.my_green)

Must be:
R.id.red_button -> findViewById<TextView>(R.id.box_three_text).setBackgroundResource(R.color.my_red)
R.id.yellow_button -> findViewById<TextView>(R.id.box_four_text).setBackgroundResource(R.color.my_yellow)
R.id.green_button -> findViewById<TextView>(R.id.box_five_text).setBackgroundResource(R.color.my_green)

**In which lesson and step of the codelab can this issue be found?**
Lesson 02.3
12. Task: Add click handlers to the buttons

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. What version of Android Studio are you using? - 4.1.3
2. What API level are you targeting? 19

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by Vikscripts** [comment] 2021-03-25 23:22
This is a duplicate of the below issue #462 - also other solutions are shown there :
https://github.com/google-developer-training/android-kotlin-fundamentals-apps/issues/462

**Closed** 2023-07-24 17:23 UTC
