### ISSUE TITLE
Android Kotlin Fundamentals codelab: 04.2 Complex lifecycle situations

### ISSUE THREAD

**Issue by reknoZ** [google-developer-training/android-kotlin-fundamentals-apps#86] opened 2020-03-29 15:18 UTC
**Describe the problem**
App won't restore data from bundle.
When running in Debug mode, I can see the app executes the three `outState.putInt` statements, but in `onCreate`, it skips the three `getInt` statements, because `savedInstanceState` is null.

**In which lesson and step of the codelab can this issue be found?**
Codelabe 04.2 Complex lifecycle situations
5. Task Simulate app shutdown and use onSaveInstanceState()
Step 3. Use onCreate() to restore bundle data
2. Scroll up to `onCreate()` ....

**How to reproduce?**
Follow the instructions.

**Versions**
1. What version of Android Studio are you using? 3.6.3
2. What API level are you targeting? 29

**Additional information**
This may be related to the previous Issue I posted, namely that the `adb` command doesn't cause the log to show an `onDestroy()` message.

**codelab:** android-kotlin-fundamentals

**Comment by KseniaKrasotina** [comment] 2020-05-11 16:15
I agree with reknoZ.

App does not even save data in a bundle. When my application is in a background (i press < button on a emulator), onDestroy() is called and the data is not saved in the bundle 

Versions

What version of Android Studio are you using? 3.6.3
What API level are you targeting? 29

**Comment by kkuan2011** [comment] 2020-08-11 07:52
Duplicate of #283

**Closed by kkuan2011** 2020-08-11 07:52 UTC
