### ISSUE TITLE
Android Kotlin Fundamentals codelab: Start an external activity lesson has invalid dependency classpath

### ISSUE THREAD

**Issue by berkcosar** [google-developer-training/android-kotlin-fundamentals-apps#186] opened 2020-05-31 11:16 UTC
**Describe the problem**
Safe args' dependency's class path is not valid.

**In which lesson and step of the codelab can this issue be found?**
03.3 + Task 3.
Step 2

**How to reproduce?**
Adding dependency as
`classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`
fails gradle to sync.
Error is:
> A problem occurred configuring root project 'AndroidTrivia-Starter'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find android.arch.navigation:navigation-safe-args-gradle-plugin:2.2.2.
>      Searched in the following locations:
>        - https://dl.google.com/dl/android/maven2/android/arch/navigation/navigation-safe-args-gradle-plugin/2.2.2/navigation-safe-args-gradle-plugin-2.2.2.pom
>        - https://dl.google.com/dl/android/maven2/android/arch/navigation/navigation-safe-args-gradle-plugin/2.2.2/navigation-safe-args-gradle-plugin-2.2.2.jar
>        - https://jcenter.bintray.com/android/arch/navigation/navigation-safe-args-gradle-plugin/2.2.2/navigation-safe-args-gradle-plugin-2.2.2.pom
>        - https://jcenter.bintray.com/android/arch/navigation/navigation-safe-args-gradle-plugin/2.2.2/navigation-safe-args-gradle-plugin-2.2.2.jar
>      Required by:
>          project :
> 

**Versions**
Android Studio 3.6.2
navigationVersion = '2.2.2'
minSdkVersion 19
targetSdkVersion 28

**Comment by JamieSmithGCU** [comment] 2020-06-26 11:58
Make sure you are using the most up to date version (found here: https://developer.android.com/jetpack/androidx/releases/navigation)

Follow the declaring dependencies section exactly for Kotlin or Java. Also make sure the $navigationVersion is defined as navigationVersion in top of Build Gradle Project file in in ext {}.

For example, in Build Gradle Project file:
ext {
       ...
        nav_version = '2.3.0-rc01'
}
...
dependencies {
        classpath "com.android.tools.build:gradle:$gradleVersion"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
}

and in Build Gradle App file:
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-kapt'

apply plugin: "androidx.navigation.safeargs.kotlin" //ENSURE THIS IS HERE

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "androidx.appcompat:appcompat:$supportlibVersion"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0-beta01'
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation "com.google.android.material:material:1.0.0-rc01"
    implementation "com.google.android.material:material:$supportlibVersion"
}

Hope this works.

**Comment by lukelima** [comment] 2020-08-06 00:31
Hi @JamieSmithGCU ! Your answer made it work for me ! Thanks a lot! Maybe we should update codelabs lesson since the .kotlin in "apply plugin: "androidx.navigation.safeargs.kotlin" //ENSURE THIS IS HERE" made a difference and it is not there!

> Make sure you are using the most up to date version (found here: https://developer.android.com/jetpack/androidx/releases/navigation)
> 
> Follow the declaring dependencies section exactly for Kotlin or Java. Also make sure the $navigationVersion is defined as navigationVersion in top of Build Gradle Project file in in ext {}.
> 
> For example, in Build Gradle Project file:
> 
> `ext {`
> `...`
> `nav_version = '2.3.0-rc01'`
> `}`
> `...`
> `dependencies {`
> `classpath "com.android.tools.build:gradle:$gradleVersion"`
> `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`
> `classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"`
> `}`
> 
> and in Build Gradle App file:
> `apply plugin: 'com.android.application'`
> `apply plugin: 'kotlin-android'`
> `apply plugin: 'kotlin-kapt'`
> `apply plugin: "androidx.navigation.safeargs.kotlin" //ENSURE THIS IS HERE`
> 
> `dependencies {`
> ` ...`
> ` implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"`
> ` implementation "androidx.navigation:navigation-ui-ktx:$nav_version"`
> `}`
> 
> Hope this works.

**Comment by kkuan2011** [comment] 2020-08-11 08:57
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 08:57 UTC
