### ISSUE TITLE
Android Kotlin Fundamentals codelab: 03.3.3

### ISSUE THREAD

**Issue by eugene-ma** [google-developer-training/android-kotlin-fundamentals-apps#155] opened 2020-05-10 16:13 UTC
**Describe the problem**
In step 2 of part 3 of the 03.3 codelab ("Start an external activity"), the following code listed to copy and paste into the project-level `build.gradle` file causes building to fail:
`classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**In which lesson and step of the codelab can this issue be found?**
Lesson 3.3, section 3, step 2.

**How to reproduce?**
Do step 2 listed in the codelab (which involves copying and pasting two separate lines of code).

**Versions**
1. What version of Android Studio are you using? 3.6.3
2. What API level are you targeting?
        minSdkVersion 19
        targetSdkVersion 28

**Additional information**
To fix it, I pasted the following code instead, which I got from the documentation linked in that section of the codelab (https://developer.android.com/guide/navigation/navigation-pass-data#Safe-args):
`classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**codelab:** android-kotlin-fundamentals 03.3.3

**Comment by kkuan2011** [comment] 2020-08-11 05:20
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 05:20 UTC
