### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ABernartt** [google-developer-training/android-kotlin-fundamentals-apps#214] opened 2020-06-18 16:17 UTC
**Describe the problem**
The codelab for the "Guess the Word" App (which teaches about Viewmodels) uses the ViewModelProviders method to instantiate the viewmodel. However, this method was deprecated,

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory

**Versions**
1. What version of Android Studio are you using?
3.6.3
2. What API level are you targeting?
min - 19
max - 29

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:01
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 06:01 UTC
