### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by jordicollmarin** [google-developer-training/android-kotlin-fundamentals-apps#198] opened 2020-06-06 16:15 UTC
**Describe the problem**
Wrong viewModel variable is being used.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.3: Data binding with ViewModel and LiveData (Task 5)

**How to reproduce?**
android:text="@{@string/score_format(gameViewModel.score)}"

**Versions**
1. What version of Android Studio are you using? No needed
2. What API level are you targeting? No needed

**Additional information**
In score_fragment you are using the gameViewModel and you should use scoreViewModel and its variable 'score'.

**codelab:** android-kotlin-fundamentals

**Comment by jordicollmarin** [comment] 2020-06-06 16:17
The problem isn't in the code, but in the codelab! :)

**Comment by kkuan2011** [comment] 2020-08-11 08:04
Duplicate of #197

**Closed by kkuan2011** 2020-08-11 08:04 UTC
