### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by aminsoheyli** [google-developer-training/android-kotlin-fundamentals-apps#47] opened 2020-02-16 14:13 UTC
**Describe the problem**

![mistake3](https://user-images.githubusercontent.com/42641117/74606193-94a71e80-50e3-11ea-97cc-926ccdf78168.PNG)

You missed the following line of code at the first line of try block as marked in the picture:
```kotlin
val listResult = getPropertiesDeferred.await()
```

**In which lesson and step of the codelab can this issue be found?**
Lesson 8.1 + task 6+ step 2.

**How to reproduce?**
Just add the following code to the first line of the try block:
```kotlin
val listResult = getPropertiesDeferred.await()
```

The complete `getMarsRealEstateProperties()` method now looks like this:

```kotlin
private fun getMarsRealEstateProperties() {
   coroutineScope.launch {
       var getPropertiesDeferred = 
          MarsApi.retrofitService.getProperties()
       try {          
           val listResult = getPropertiesDeferred.await()
           _response.value = "Success: ${listResult.size} Mars properties retrieved"
       } catch (e: Exception) {
           _response.value = "Failure: ${e.message}"
       }
   }
}
```

**Additional information**
Link: https://codelabs.developers.google.com/codelabs/kotlin-android-training-internet-data/#5

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:04
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:04 UTC
