### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by rumbledot** [google-developer-training/android-kotlin-fundamentals-apps#335] opened 2020-08-22 20:48 UTC
**Describe the problem**
assigning setBackgroundResource directly to a view's ID name
box_three_text.setBackgroundResource(R.color.my_red)

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 02.3: Constraint layout using the Layout Editor
12. Task: Add click handlers to the buttons

**How to reproduce?**

**Versions**
Android Studio 4.0.1
android {
    compileSdkVersion 29
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.rumbledot.logger"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by jtavva** [comment] 2020-09-15 17:47
@rumbledot 
Thank you for reaching out to us.
Duplicate of #399

**Comment by jtavva** [comment] 2020-09-15 17:48
@rumbledot 
Thank you for reaching out to us.
Can you explain what is issue that you are facing.

**Comment by rumbledot** [comment] 2020-09-19 01:08
I have this worked out.
No longer a problem for me.

**Comment by jtavva** [comment] 2020-10-21 00:09
@rumbledot 
Thank you for reaching out to us.
Glad that you were able to work it out.

**Closed by jtavva** 2020-10-21 00:09 UTC
