### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by nmakhari** [google-developer-training/android-kotlin-fundamentals-apps#128] opened 2020-04-26 00:40 UTC
**Describe the problem**
Dependency update has deprecated the code contained.

**In which lesson and step of the codelab can this issue be found?**
Lesson # 5.01 Task # 5, Step# 4, Bullet # 2

**How to reproduce?**
viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)
The above line is no longer valid in the current supported version we were indicated to seek out and use

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:13
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 05:13 UTC
