### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by anprimordi** [google-developer-training/android-kotlin-fundamentals-apps#251] opened 2020-07-15 06:42 UTC
**Describe the problem**
1. Safeargs dependency is obsolete and should be renewed to:

```
dependencies {
   ...
   classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}
```

2. This codelab used kotlin, therefore plugin should be changed to:
`apply plugin: 'androidx.navigation.safeargs.kotlin'`

**In which lesson and step of the codelab can this issue be found?**
Lesson 03.3: Start an external activity + step 2.

**How to reproduce?**
Dependency is obsolete.

**Versions**
Android Studio 4.0.1
Target SDK Version 30

**Additional information**
~

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:27
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 07:27 UTC
