### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by barryooog** [google-developer-training/android-kotlin-fundamentals-apps#168] opened 2020-05-20 15:12 UTC
**Describe the problem**
When using Android studio 3.6.3 when you create a new project using the basic activity template it now generates a project that using fragments and nav elements between them. This isn't reflected in the rest of the lesson.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.4: Learn to help yourself
Step 3

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
1. Android studio 3.6.3
2. minSdkVersion 19
    targetSdkVersion 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:43
Duplicate of #107

**Closed by kkuan2011** 2020-08-11 08:43 UTC
