### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by houssam-MIMI** [google-developer-training/android-kotlin-fundamentals-apps#200] opened 2020-06-08 12:16 UTC
**Describe the problem**
  the probleme is  when I use safe Args classe generated  in the methode onCreateView , all Binding Classes are lost , when I want to instialise the binding variable , system could not find  for exemple 
 val binding = DataBindingUtil.inflate<FragmentGameBinding>(inflater, R.layout.fragment_game, container, false)  , here FragmentGameBinding are not found 

**In which lesson and step of the codelab can this issue be found?**
03.03 + 3

**How to reproduce?**
What are the exact steps to reproduce the problem?

**Versions**
8.0.0
2. What API level are you targeting?
28
**Additional information*
what the relation between SafeArgs and the binding concept 

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:56
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 08:56 UTC
