### ISSUE TITLE
1.4 Learn to Help Yourself: Basic Activity template has changed

### ISSUE THREAD

**Issue by pratyush8112000** [google-developer-training/android-kotlin-fundamentals-apps#132] opened 2020-04-28 12:06 UTC
**Describe the problem**
After having downloaded Android Studio 3.6.3 and exploring the course given in the specified codelab, the description of the 'Basic Activity' doesn't match with the one I am presented with and hence, it makes it difficult for me to follow along.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.4: Learn to help yourself
Step No. 3: Task: Use project templates

**How to reproduce?**
Update the Basic Activity architecture description

**Versions**
1. Android Studio 3.6.3
2. 29

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:17
Duplicate of #107

**Closed by kkuan2011** 2020-08-11 05:17 UTC
