### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by danvn** [google-developer-training/android-kotlin-fundamentals-apps#138] opened 2020-04-30 00:19 UTC
**Describe the problem**
Missing line of code

**In which lesson and step of the codelab can this issue be found?**
8.1 Step 6

**How to reproduce?**
Look at code block after "The complete getMarsRealEstateProperties() method now looks like this:" 

**Versions**
1. What version of Android Studio are you using?
2. What API level are you targeting?

**Additional information**
Missing the line `var listResult = getPropertiesDeferred.await()` in the try block

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:14
Duplicate of #36

**Closed by kkuan2011** 2020-08-11 07:14 UTC
