### ISSUE TITLE
Android Kotlin Fundamentals codelab: deprecated syntax used 

### ISSUE THREAD

**Issue by gcrosti** [google-developer-training/android-kotlin-fundamentals-apps#180] opened 2020-05-28 15:55 UTC
**Describe the problem**
This syntax to instantiate a ViewModel is deprecated according to the Android docs:
ViewModelProviders.of(this).get(GameViewModel::class.java)
Would love guidance on what I should use! I replaced with:
viewModel = ViewModelProvider(this).get(GameViewModel::class.java)

**In which lesson and step of the codelab can this issue be found?**
Step 5 of Android Fundamentals 05.1

**How to reproduce?**
na

**Versions**
na

**Additional information**
na

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:12
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 06:12 UTC
