### ISSUE TITLE
Update to use Fragment property delegate to get ViewModel

### ISSUE THREAD

**Issue by ceruleanotter** [google-developer-training/android-kotlin-fundamentals-apps#25] opened 2020-01-28 23:41 UTC
Update to use Fragment property delegate to get ViewModel:
https://developer.android.com/reference/kotlin/androidx/fragment/app/package-summary#viewmodels

**Comment by kkuan2011** [comment] 2020-08-11 06:24
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 06:24 UTC
