### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by EmilioNegron** [google-developer-training/android-kotlin-fundamentals-apps#223] opened 2020-06-24 13:24 UTC
**Describe the problem**
On Page 6 of codelab "Android Kotlin Fundamentals 08.1: Getting data from the internet", there is a line that states:
"The complete getMarsRealEstateProperties() method now looks like this:", and a snapshot of the "getMarsRealEstateProperties()" method is displayed. This snapshot is missing the "var listResult = getPropertiesDeferred.await()" statement needed inside of the "try - catch".  Also, the "MarsApi.retrofitService.getProperties()" statement seems to be deprecated with the latest version update for lib "version_kotlin_coroutines", which in my case was updated to "1.3.0".

**In which lesson and step of the codelab can this issue be found?**
"Android Kotlin Fundamentals 08.1: Getting data from the internet" + "Step 2: Update MarsApiService and OverviewViewModel"

**How to reproduce?**
Just compile the code using the suggested method called "getMarsRealEstateProperties()". You should receive the following compile errors:
e: /Users/XXXXXXXXXXX/AndroidStudioProjects/Kotlin_Fundamentals_starter/MarsRealEstate-Starter/app/src/main/java/com/example/android/marsrealestate/overview/OverviewViewModel.kt: (61, 45): Unresolved reference: getProperties
Unresolved reference: listResult

**Versions**
1. What version of Android Studio are you using?
4.0
2. What API level are you targeting?
29
**Additional information**
Not difficult to fix:
Replace method snapshot with:

/**
 * Sets the value of the status LiveData to the Mars API status.
 */
private fun getMarsRealEstateProperties() {
    coroutineScope.launch {
        var getPropertiesDeferred =
                MarsApi.retrofitService.**getPropertiesAsync()**
        try {
            var listResult = getPropertiesDeferred.await()
            _response.value =
                    "Success: ${listResult.size} Mars properties retrieved"
        } catch (e: Exception) {
            _response.value = "Failure: ${e.message}"
        }
    }
}

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:35
Thanks Emilio! This is a known issue so will mark as Duplicate of #36

**Closed by kkuan2011** 2020-08-11 08:35 UTC
