### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Jackrjie** [google-developer-training/android-kotlin-fundamentals-apps#42] opened 2020-02-14 17:39 UTC
**Describe the problem**
According to the latest view model version, should be using ViewModelProvider()

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 05.1: ViewModel and ViewModelFactory, Step 5

**How to reproduce?**
Change ViewModelProviders.of() to ViewModelProvider() with the latest view model version

**Versions**
1. What version of Android Studio are you using? 3.5
2. What API level are you targeting? 29

**Additional information**
Nice course by google, anyway, I very enjoy playing this codelab

**codelab:** android-kotlin-fundamentals

**Comment by flplatet** [comment] 2020-04-13 23:27
Duplicate of #29

**Closed** 2020-05-14 20:59 UTC
Labels: duplicate
