### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by davidbacter01** [google-developer-training/android-kotlin-fundamentals-apps#142] opened 2020-05-01 19:57 UTC
**Describe the problem**
A clear and concise description of what the problem is:
When creating a new project (Empty Activity) it is said "select Use AndroidX artifacts checkbox"
however there is no such option.

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 01.1: Get started  step 4.

**How to reproduce?**
Follow the instructions.

**Versions**
1. What version of Android Studio are you using?
AndroidStudio 3.6
2. What API level are you targeting?
4.4 kitkat

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 07:13
Duplicate of #278

**Closed by kkuan2011** 2020-08-11 07:13 UTC
