### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by fmmarzoa** [google-developer-training/android-kotlin-fundamentals-apps#267] opened 2020-07-25 17:12 UTC
**Describe the problem**
The method to kill an app with adb doesn't seem to work

**In which lesson and step of the codelab can this issue be found?**
4.02 / 5 / 5

**How to reproduce?**
Just execute this in a terminal as suggested in the lesson:
adb shell am kill com.example.android.dessertclicker

Nothing happens, no matter the app is in foreground or background, Android Studio does not notify the app has stopped, and if you go back to the app it calls OnRestart instead of OnCreate as the lesson says it should.

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28, that's the one the started sample code uses

**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:47
Duplicate of #156

**Closed by kkuan2011** 2020-08-11 05:47 UTC
