### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by Shabinder** [google-developer-training/android-kotlin-fundamentals-apps#210] opened 2020-06-16 20:13 UTC
**Describe the problem**
Log.i("GameFragment", "Called ViewModelProviders.of")
viewModel = ViewModelProviders.of(this).get(GameViewModel::class.java)

In here, **ViewModelProviders.of** is being notified as deprecated so please update codelab too.
**In which lesson and step of the codelab can this issue be found?**
lesson 5.1 , Task 5

**How to reproduce?**
What are the exact steps to reproduce the problem?
just update all dependencies and while configuring you will face this.

**Versions**
1. What version of Android Studio are you using?
v4.0
2. What API level are you targeting?
29

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 06:44
Duplicate of #33

**Closed by kkuan2011** 2020-08-11 06:44 UTC
