### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by dcigdp** [google-developer-training/android-kotlin-fundamentals-apps#295] opened 2020-08-08 18:59 UTC
**Describe the problem**
A clear and concise description of what the problem is.
Androidx dependencies should be used consistently. There is a reference to adding classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
which causes a build error. Replacing it with 
classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
resolved the error.  The next step 
apply plugin: 'androidx.navigation.safeargs'
references Androidx, so it seems the previous step should as well.

**In which lesson and step of the codelab can this issue be found?**
Lesson number + step number.
03.03

**How to reproduce?**
What are the exact steps to reproduce the problem?
1.In Android Studio, open the project-level build.gradle file.
2.Add the navigation-safe-args-gradle-plugin dependency, as shown below:
  / Adding the safe-args dependency to the project Gradle file
dependencies {
   ...
classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

}
3.Project will not sync
**Versions**
1. What version of Android Studio are you using?
4.0.1
2. What API level are you targeting?
28
**Additional information**

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 08:26
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 08:26 UTC
