### ISSUE TITLE
Android Kotlin Fundamentals codelab: 

### ISSUE THREAD

**Issue by ken-brown** [google-developer-training/android-kotlin-fundamentals-apps#279] opened 2020-07-31 19:11 UTC
**Describe the problem**
classpath statement results in not finding the library

**In which lesson and step of the codelab can this issue be found?**
Android Kotlin Fundamentals 03.3 + step number 3.

**How to reproduce?**
Follow instructions in Step 3 regarding of including classpath statement:
        classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

Result:
_Could not find android.arch.navigation:navigation-safe-args-gradle-plugin:2.3.0.

Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/android/arch/navigation/navigation-safe-args-gradle-plugin/2.3.0/navigation-safe-args-gradle-plugin-2.3.0.pom
  - https://jcenter.bintray.com/android/arch/navigation/navigation-safe-args-gradle-plugin/2.3.0/navigation-safe-args-gradle-plugin-2.3.0.pom
Required by:
    project_ 

**Versions**
1. What version of Android Studio are you using? 4.0.1
2. What API level are you targeting? 28

**Additional information**
If you change the class path to the below statement, the code compiles:
 classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"

**codelab:** android-kotlin-fundamentals

**Comment by kkuan2011** [comment] 2020-08-11 05:44
Duplicate of #35

**Closed by kkuan2011** 2020-08-11 05:44 UTC
